[package]
name = "darksol"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.26"
solana-poseidon = "2.2.0"
primitive-types = "0.12"

ark-std = "0.5"
ark-bn254 = "0.5"
ark-bls12-377 = "0.5"
ark-ff = "0.5.0"
ark-crypto-primitives = { version = "0.5", features = ["crh", "merkle_tree"] }
hex = "0.4"
ark-r1cs-std = "0.5.0"
sha3 = "0.10.8"
ethp = "0.1.0"
borsh = "1.5.5"
[lib]
crate-type = ["cdylib", "lib"]
