[package]
name = "verification"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.1"
solana-program = "2.2.0"
groth16-solana = {git = "https://github.com/veil-protocol-privacy/groth16-solana"}
ark-ec = "0.3.0"
ark-ff = "0.3.0"
ark-bn254 = "0.3.0"